version: '3'

services:
  database:
    image: mysql:8
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd123!@#
      MYSQL_DATABASE: aurora-database
      MYSQL_USER: aurora
      MYSQL_PASSWORD: aurora123!@#
      YZ: 'Asia/Seoul'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  nestjs:
    build:
      context: ./aurora-backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - PORT=8822
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=aurora
      - DB_PW=aurora123!@#
    ports:
      - 8822:8822
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    restart: always